fallback = 'ï‹'
[matching]
'discord' = 'ï’'
#î„± î„¹ î…£ î†… î†° îˆ— îˆ« îˆ± îˆ° îˆ´ îˆµ îˆ¸ î‰€ îˆ¿ î‰… î‰Š î‰¦ î‰¨ î‰± î‰² î‰° îŠŒ îŠŠ îŠ îŠ îŠ¦ îŠ· î‹… î‹Š î î® î¾ î¿ î‘… î—¿ î˜“ î˜• î˜£ î˜ª î˜« îœ î­² î®¦ ï€ ï€• ï€˜ ï€£ ï€° ï€¾ ï€½ ï ï€ ï¶ ï² ï„› ï…ª ï…§ ï†¶ ï‡­ ï‡¬ ï‡« ï‡¼ ï‡¸ ï‰¨ ï‰° ïŠ ïŠ” ïŒ² ï’ ï ïŠ ï­ ï¶ ï”¿ ï–¬ ï–¼ ï—’ ï—œ ï—š ï¦ ïŸ‚ ï ‹
#Potential game icons îº îŠŒ ï€˜ ï² ïƒ» ï†— ï†¨ ïˆ› ïˆœ ï—Š ï—« ï˜Š ï›‹ ïœ’ ïœ¹ ïŸ î´ ïŸ ï˜š î… îŠ† î‰²
'steam_app_1817070' = 'ó±‡ª'
'steam_app_1817190' = 'ó±‡ª'
'steam_app_783770' = 'ó°œƒ'
'steam_app_714010' = 'ó°œƒ'
'steam_app_2281730' = 'ó°œƒ'
'CombatMaster.x86_64' = 'ó°œƒ'
'steam_app_1266700' = 'ó°¢š'
'steam_app_1872550' = 'ó°¢š'
'steam_app_803330' = 'ó°¢š'
'steam_app_246620' = 'îŠ†'
'lmirtechconsole.exe' = 'ï„ˆ'
'Anydesk' = 'ï„ˆ'
'org.twosheds.iwgtk' = 'ï‡«'
'at.yrlf.wl_mirror' = 'ï„ˆ'
'steam' = 'ï†¶'
'Steam' = 'ï†¶'
'steamwebhelper' = 'ï†¶'
'vlc' = 'ó°•¼'
'org.qbittorrent.qBittorrent' = 'ó±‘¤'
'Thunderbird' = 'ó°‡®'
'thunderbird' = 'ó°‡®'
'Postman' = 'ó°‡®'
'Insomnia' = 'ïˆ¶'
'Bitwarden' = 'ï„²'
'Slack' = 'ó°’±'
'Code' = 'î–'
'code-oss' = 'î–'
'Spotify' = 'ï†¼'
'/NVIM ?\w*/' = 'î˜«'
'/npm/' = 'ï¹'
'/node/' = 'ï¹'
'/yarn/' = 'ï¹'
'Alacritty' = 'î¢'
'foot' = 'î¢'
'org.telegram.desktop' = 'îˆ—'
'telegramdesktop' = 'îˆ—'
'Telegram' = 'îˆ—'
'Wfica' = 'ïŠ'
'org.remmina.Remmina' = 'ïŠ'
'SchildiChat' = 'ï³'
'Element' = 'ï³'
'/(?i)Element.*/' = 'ï³'
'nheko' = 'ï³'
'/ - YouTube â€” Mozilla Firefox' = 'ï…ª'
'/ - YouTube.*Chromium/' = 'ï…ª'
'/ - YouTube.*Iridium/' = 'ï…ª'
'/Firefox .*Private Browsing/' = 'ó°ˆ‰'
'/(?i)Google Drive.*Firefox/' = 'ïª'
'/(?i)Google Calendar.*Firefox/' = 'ï³'
'/(?i)MAX.*Iridium/' = 'ïƒ‚'
'/(?i)MAX.*Chromium/' = 'ïƒ‚'
'/(?i)Dashboards -.*Iridium/' = 'ï‚€'
'/(?i)Dashboards -.*Chromium/' = 'ï‚€'
'/Twitter/' = 'ï‚™'
'/(?i)reddit.*Firefox/' = 'ïŠ'
'/(?i)drive.*Firefox/' = 'ïª'
'/(?i)Google Play.*Firefox/' = 'ï«'
'/(?i)Github/' = 'ï‚›'
'/Google/' = 'ï† '
'yakyak' = 'ó°‹‰'
'copyq' = 'ó°…‡'
'Microsoft Teams - Preview' = 'ó°Š»'
'Microsoft Teams - Insiders' = 'ó°Š»'
'teams-for-linux' = 'ó°Š»'
'clonehero' = 'ó°‹„'
'/trash:/ .*Dolphin/' = 'ï‡¸'
#'/home/.*Documents â€“ Dolphin/' = 'ï…›'
#ïŠï‹ïŒïïïïï‘ï“ï–ï—ï˜
'org.kde.dolphin' = 'ó°‰‹'
'/pcmanfm/' = 'ó°‰‹'
'pcmanfm-qt' = 'ó°‰‹'
'pcmanfm-gtk3' = 'ó°‰‹'
'/Pcmanfm/' = 'ó°‰‹'
'/home/.*Dolphin/' = 'ï€•'
'org.kde.ark' = 'ï†‡'
'firefox' = 'î€‡'
'Nightly' = 'î€‡'
'firefoxdeveloperedition' = 'î€‡'
'Google-chrome' = 'ï‰¨'
'Chromium' = 'ï‰¨'
'Chromium-browser' = 'ï‰¨'
'org.kde.kcharselect' = 'ï“•'
'gucharmap' = 'ï“•'
'Zim' = 'ó°ª'
'image-roll' = 'î”¯'
'com.github.weclaw1.ImageRoll' = 'î”¯'
'pavucontrol' = 'ï€¨'
'obs' = 'ó°»‚'
'galculator' = 'ó°ƒ¬'
'mpv' = 'ó°Œ'
'yuzu' = 'ï„›ï¸'
'rpcs3' = 'ï„›ï¸'
'blueberry.py' = 'ï–®'
'com.github.wwmm.easyeffects' = 'ï€'
'citra' = 'ï„›ï¸'
'Cemu' = 'ï„›ï¸'
'wdisplays' = 'ï'
'Pinta' = 'ó°ƒ£'
'pinta' = 'ó°ƒ£'
'dolphin-emu' = 'ï„›ï¸'
'GParted' = 'ó°‹Š'
'/GParted/' = 'ó°‹Š'
'stoken-gui' = 'ó°Œ†'
'polkit-gnome-authentication-agent-1' = 'ï€£'
'gcr-prompter' = 'ï€£'
'org.inkscape.Inkscape' = 'îŠ¦'
'audacity' = 'îˆ´'
'anki' = { type = 'generic', value = 'ï€…'}
'/(?i)settings*/' = { type = 'generic', value = 'ï€“'}
'/(?i)calendar*/' = { type = 'generic', value = 'ï³'}
'org.qutebrowser.qutebrowser' = 'ï’„'
'whatsapp-for-linux' = 'ïˆ²'
'Ardour-6.9.0' = 'îˆ´'
'Gimp' = 'ï”¿'
'/pdf/' = 'ï‡'
'/exe/' = 'ó°¡¶'
'/Steam setup/' = 'ï†¶'
#do all the dolphin folders ï—¿
#î‚¢
#î‰Š
#î“¥
#î˜Š
#î™
#î™²
#îšª
#îœ²
#î–
#î¢
#î©¡
#î©¼
#î«„
#î¬
#î­²
#ï€°
#ï€¾
#ï„¾
#ï‡¬
#ï–®
#ïŒ²
#ï‘†
#ï‘ˆ
#ï’š
#ï“¢
#ï“´
#ï–½
#ï—¢
#ï—¡
#ï—»
#ï—¿
#ï˜ƒ
#ï™
#ï›‚
#ïœˆ
#ïœ‡
#ïœ¯
#ïŠ
#ïŸŠ
#ïŸ
#ïŸ
#ï¡«
#ï¡¬
#ï¢€
#ï£—
#ï£©
#ï£ª
#ï£®
#ï¡¸
#ï£›
#ï£©
#ï£ª
#ï£«
#ï¡•
#ï …
#ï Š
#ïŸ¸
#ïŸ´
#ïŸµ
#ïŸ‰
#ïˆ
#ïœ¯
#ïœ˜
#ïœˆ
#ï›­
#ï™º
#ï™
#ï™†
#ï”·
#ï“£
#ï’š
#ï’…
#ï‘ˆ
#ï‘†
#ï½
#ï‚
#ï
#ï†¶
#ï€€
#î¢
#î•
#î¢
#îšª
#îšƒ
#î™Ÿ
#î—¿
#î—¾
#î”¯
#î’¨
#î‘…
#î‹…
#îŠ¦
#îŠ
#î‰·
#î‰¯
#î‰Ÿ
#î‰
#î‰„
#î‰€
#îˆ¿
#îˆº
#î…£
#î„±
#î´
#î¬
#îš
#ï‰°
#ï‡¬
#îš¥
#îš¦
#ï–
#ï’œ
#ïµ
#ïš’
#ïšŠ
#ï—«
#î„±
#î˜‚
#î¥
#î®¦
#ï€¾
#ï€½
#ï€
#ï„›
#ï…„
#ï†¹
#ï‰¨
#ï”²
#ï—¡
#ïœ®
#ï–
#ïŸ´
#ï¢†

#â„ï¸
#ï›
#ï“•
#ï“¸
#ï º
#ï³
#ï†’
#ï‡…
#ï‡‡
#ï˜’
#ï„³
#ï…›
#â˜ïƒ‚
#ï—ï¸
#ï‹­
#ïŒ‚
#ï
#ïª
#ï«
#ï¼
#ï‚
#ï»
#â˜ï¸
#ï€™ï¸
#âœ‰ï¸
#ğŸ—©ï¸
#ï¡£ï¸
#ï‚…ï¸
#ï‡¸ï¸
#âš™ï¸
#ï‚€ï¸
#ï‰ºï¸
#ï‡‡ï¸
#ï‰ºï¸
#ï‹­ï¸
#ï³ï¸
#ğŸ–Œï¸
#ï– ï¸
#ï‚™
#ï‚•
#ï‚¬
#ï²
#ï€¯
#ïƒ¦
#ïƒ©
#ïƒ§
#ï„œ
#ï„°
#ï„±
#ï…‹
#ï…
#ï…­
#ï…³
#ï…¾
#ï†¾
#ï‡
#ï‡‚
#ï‡ƒ
#ï‡„
#ï‡…
#ï‡†
#ï‡‡
#ï‡ˆ
#
#ï‡
#ï‡«
#ï‡­
#ïˆ„
#ïˆ…
#ï‰„ï‰ƒï‰‚ï‰ï‰€
#ïŠ‹
#ïŠ
#ïŸ
#ïµ
#ï…
#ïŸ
#ï’
#ï¹
#ï–’
#ïš©
#ï€

